export default [
  {
    name: "Oulun Eläinklinikka",
    url: "https://www.ouluek.fi/",
    phone: "(08) 554 5850",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "7:00-21:00" },
      { weekday: "Tiistai", hours: "7:00-21:00" },
      { weekday: "Keskiviikko", hours: "7:00-21:00" },
      { weekday: "Torstai", hours: "7:00-21:00" },
      { weekday: "Perjantai", hours: "7:00-21:00" },
      { weekday: "Lauantai", hours: "9:00-17:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Metsokankaantie 3",
    postalCode: "90420",
    city: "Oulu",
  },
  {
    name: "Eläinlääkäriasema Kamu Oy",
    url: "http://www.oulunkamu.fi/",
    phone: "020 1213900",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "7:00-20:00" },
      { weekday: "Tiistai", hours: "7:00-20:00" },
      { weekday: "Keskiviikko", hours: "7:00-20:00" },
      { weekday: "Torstai", hours: "7:00-20:00" },
      { weekday: "Perjantai", hours: "7:00-20:00" },
      { weekday: "Lauantai", hours: "7:00-20:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Kansankatu 48",
    postalCode: "90100",
    city: "Oulu",
  },
  {
    name: "Eläinlääkäriasema Lemmikki Oy",
    url: "http://www.elainlaakariasemalemmikki.fi/",
    phone: "08 311 5866",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "9:00-17:00" },
      { weekday: "Tiistai", hours: "9:00-17:00" },
      { weekday: "Keskiviikko", hours: "9:00-17:00" },
      { weekday: "Torstai", hours: "9:00-17:00" },
      { weekday: "Perjantai", hours: "9:00-14:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "9:00-19:00" },
    ],
    address: "Teknologiantie 5 B",
    postalCode: "90570",
    city: "Oulu",
  },
  {
    name: "Pieneläinklinikka Pirkkalan Elli",
    url:
      "https://evidensia.fi/elainlaakariasema/pienelainklinikka-pirkkalan-elli/",
    phone: "0201 750 350",
    email: "partola@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–20:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–20:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Naistenmatkantie 76",
    postalCode: "33950",
    city: "Tampere",
  },
  {
    name: "Pohjois-Suomen Eläinsairaala",
    url: "https://evidensia.fi/elainlaakariasema/elainsairaala-evidensia-oulu/",
    phone: "0201 750 170",
    email: "oulu@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Tiistai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Keskiviikko", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Torstai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Perjantai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Lauantai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Sunnuntai", hours: "Avoinna ympäri vuorokauden" },
    ],
    address: "Idealinja 13",
    postalCode: "90410",
    city: "Oulu",
  },
  {
    name: "Lohjan Pieneläinklinikka",
    url: "https://evidensia.fi/elainlaakariasema/lohjan-pienelainklinikka/",
    phone: "0201 750 120",
    email: "lohja@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "7:30–20:00" },
      { weekday: "Tiistai", hours: "7:30–20:00" },
      { weekday: "Keskiviikko", hours: "7:30–20:00" },
      { weekday: "Torstai", hours: "7:30–20:00" },
      { weekday: "Perjantai", hours: "7:30–20:00" },
      { weekday: "Lauantai", hours: "9:00–15:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Laurinkatu 35",
    postalCode: "08100",
    city: "Lohja",
  },
  {
    name: "Eläinlääkäriasema Evidensia Naantali",
    url: "https://evidensia.fi/elainlaakariasema/evidensia-naantali/",
    phone: "0201 750 130",
    email: "naantali@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8.30–17:00" },
      { weekday: "Tiistai", hours: "8.30–17:00" },
      { weekday: "Keskiviikko", hours: "8.30–17:00" },
      { weekday: "Torstai", hours: "8.30–17:00" },
      { weekday: "Perjantai", hours: "8.30–16:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Tullikatu 12",
    postalCode: "21100",
    city: "Naantali",
  },
  {
    name: "Eläinsairaala Vettori",
    url: "https://evidensia.fi/elainlaakariasema/elainsairaala-vettori/",
    phone: "0201 800 770",
    email: "vettori@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Tiistai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Keskiviikko", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Torstai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Perjantai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Lauantai", hours: "Avoinna ympäri vuorokauden" },
      { weekday: "Sunnuntai", hours: "Avoinna ympäri vuorokauden" },
    ],
    address: "Purokatu 3",
    postalCode: "21200",
    city: "Raisio",
  },
  {
    name: "Eläinlääkäriasema Evidensia Rauma",
    url: "https://evidensia.fi/elainlaakariasema/evidensia-rauma/",
    phone: "0201 800 810",
    email: "rauma@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–20:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–16:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Sahankatu 2",
    postalCode: "26100",
    city: "Rauma",
  },
  {
    name: "Eläinlääkäriasema Evidensia Nurmijärvi",
    url: "https://evidensia.fi/elainlaakariasema/evidensia-nurmijarvi/",
    phone: "0201 750 330",
    email: "nurmijarvi@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–20:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–20:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Kauppanummentie 6 C 1",
    postalCode: "01900",
    city: "Nurmijärvi",
  },
  {
    name: "Mäntsälän eläinlääkäriasema",
    url: "https://evidensia.fi/elainlaakariasema/mantsalan-elainlaakariasema/",
    phone: "0201 750 100",
    email: "mantsala@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–20:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–18:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Mäntymäentie 3",
    postalCode: "04600",
    city: "Mäntsälä",
  },
  {
    name: "Lahden eläinlääkäriasema",
    url: "https://evidensia.fi/elainlaakariasema/lahden-elainlaakariasema/",
    phone: "0201 800 760",
    email: "lahti@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–20:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–20:00" },
      { weekday: "Lauantai", hours: "9:00–15:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Launeenkatu 12",
    postalCode: "15100",
    city: "Lahti",
  },
  {
    name: "Eläinlääkäriasema Villimys Evidensia Lappeenranta",
    url: "https://evidensia.fi/elainlaakariasema/elainlaakariasema-villimys/",
    phone: "0201 800 750",
    email: "villimys@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "7.30–20:00" },
      { weekday: "Tiistai", hours: "7.30–20:00" },
      { weekday: "Keskiviikko", hours: "7.30–20:00" },
      { weekday: "Torstai", hours: "7.30–20:00" },
      { weekday: "Perjantai", hours: "7.30–20:00" },
      { weekday: "Lauantai", hours: "9:00–15:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Myllärinkatu 10",
    postalCode: "53550",
    city: "Lappeenranta",
  },
  {
    name: "Kouvolan eläinsairaala",
    url: "https://evidensia.fi/elainlaakariasema/kouvolan-elainsairaala/",
    phone: "020 1800740",
    email: "kouvola@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–17:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–17:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Palomäenkatu 54",
    postalCode: "45100",
    city: "Kouvola",
  },
  {
    name: "Keravan Eläinklinikka",
    url: "https://evidensia.fi/elainlaakariasema/keravan-elainklinikka/",
    phone: "0201 750 150",
    email: "kerava@evidensia.fi",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "8:00–20:00" },
      { weekday: "Tiistai", hours: "8:00–20:00" },
      { weekday: "Keskiviikko", hours: "8:00–20:00" },
      { weekday: "Torstai", hours: "8:00–20:00" },
      { weekday: "Perjantai", hours: "8:00–20:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Alikeravantie 30",
    postalCode: "04250",
    city: "Kerava",
  },
];
