export default [
  {
    name: "Oulun Eläinklinikka",
    url: "https://www.ouluek.fi/",
    phone: "(08) 554 5850",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "7:00-21:00" },
      { weekday: "Tiistai", hours: "7:00-21:00" },
      { weekday: "Keskiviikko", hours: "7:00-21:00" },
      { weekday: "Torstai", hours: "7:00-21:00" },
      { weekday: "Perjantai", hours: "7:00-21:00" },
      { weekday: "Lauantai", hours: "9:00-17:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Metsokankaantie 3",
    postalCode: "90420",
    city: "Oulu",
  },
  {
    name: "Eläinlääkäriasema Kamu Oy",
    url: "http://www.oulunkamu.fi/",
    phone: "020 1213900",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "7:00-20:00" },
      { weekday: "Tiistai", hours: "7:00-20:00" },
      { weekday: "Keskiviikko", hours: "7:00-20:00" },
      { weekday: "Torstai", hours: "7:00-20:00" },
      { weekday: "Perjantai", hours: "7:00-20:00" },
      { weekday: "Lauantai", hours: "7:00-20:00" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Kansankatu 48",
    postalCode: "90100",
    city: "Oulu",
  },
  {
    name: "Eläinlääkäriasema Lemmikki Oy",
    url: "http://www.elainlaakariasemalemmikki.fi/",
    phone: "08 311 5866",
    isOpenToday: false,
    openingHours: [
      { weekday: "Maanantai", hours: "9:00-17:00" },
      { weekday: "Tiistai", hours: "9:00-17:00" },
      { weekday: "Keskiviikko", hours: "9:00-17:00" },
      { weekday: "Torstai", hours: "9:00-17:00" },
      { weekday: "Perjantai", hours: "9:00-14:00" },
      { weekday: "Lauantai", hours: "Suljettu" },
      { weekday: "Sunnuntai", hours: "Suljettu" },
    ],
    address: "Teknologiantie 5 B",
    postalCode: "90570",
    city: "Oulu",
  },
];
